version: "3.9"

services:
  backend:
    build:
      context: ./read-dir-service
      dockerfile: Dockerfile
    container_name: backend
    ports:
      - "3000:3000"
    restart: always

  frontend:
    build:
      context: ./read-dir-client
      dockerfile: Dockerfile
    container_name: frontend
    ports:
      - "8080:80"
    depends_on:
      - backend
    restart: always
